### ISSUE TITLE
Yes, we're real big

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM-Theme#25] opened 2016-05-06 14:21 UTC
Referencing #24. Yes, we're real big. Yes we're too big. When you have a chance, please restrict our max width, collectively to like 980 or 1080 or some other common width in that range. IDC really what the final number is in that general area.

**Comment by d4mation** [comment] 2016-05-19 13:26
Here it is at `75%` width centered (Which happens to be `1080px` wide on my MacBook)

What do you think?

![image](https://cloud.githubusercontent.com/assets/7770631/15394955/af7e35a8-1da3-11e6-84a4-79fcfb8cfaa1.png)

**Comment by joelworsham** [comment] 2016-05-19 13:27
I'm totally open to you coming up with a different, better display of the staff. I've never really loved what I originally came up with anyways.

**Comment by d4mation** [comment] 2016-05-19 13:29
Yeah, back when I was handling #24 it had to be handled in a less than ideal way to get two rows. It may be best to revisit it entirely.

**Comment by joelworsham** [comment] 2016-05-19 13:31
My vote is go crazy @d4mation and make something cool.

Here's some cool people doing a cool job with it:

http://10up.com/about/
https://getflywheel.com/about/
https://wpengine.com/about-us/

**Comment by BigActual** [comment] 2016-05-19 13:59
Nice ideas Joel. Yes, Eric, I like that better.

**Comment by d4mation** [comment] 2016-05-19 14:44
Those are really slick, @joelworsham. I'm going to look into re-doing this section a bit to be more maintainable/flexible with something like those in mind.

**Comment by BigActual** [comment] 2016-05-19 15:05
I'm not for circles.

**Comment by d4mation** [comment] 2016-05-19 17:58
[How about triangles?](https://codepen.io/mikehobizal/full/EHDsu/)

Trying to think up as many different ways to handle this that won't break/look weird with odd numbers rather than even numbers&mdash;considering our potential to grow beyond the four of us.

**Comment by d4mation** [comment] 2016-05-19 18:31
Actually I think this would be way cooler:

Hovering for the details like this
![image](https://cloud.githubusercontent.com/assets/7770631/15405005/1cdb4daa-1dce-11e6-8508-1986473f95c9.png)

Arranged like this:

![image](https://cloud.githubusercontent.com/assets/7770631/15405042/42293d06-1dce-11e6-88d1-e39ee694f3b4.png)

The Hexagons give some visual interest while allowing us to add onto it in the future without things looking weird.

**Comment by brashrebel** [comment] 2016-05-19 19:59
Cool with me.

**Comment by BigActual** [comment] 2016-05-19 21:57
What about the gear in our logo?. Keeping a consistent design element instead of introducing a new one.

**Comment by d4mation** [comment] 2016-05-19 23:57
That's a great idea! I had thought about something similar, but I for some reason overlooked the gear and was just thinking the lightbulb which I thought wouldn't look right.

I'll have to be mindful of the size of the sprockets for @joelworsham's Gravatar in particular since he's off to the side. I got his looking pretty good within a hexagon

![image](https://cloud.githubusercontent.com/assets/7770631/15413169/ad53d3b6-1dfb-11e6-9faa-b53e979a6e9b.png)

but his looked pretty weird/funny in a triangle

![image](https://cloud.githubusercontent.com/assets/7770631/15413185/c27199a4-1dfb-11e6-9c28-781172c00f89.png)

I'm going to start working on building out something for a gear-shaped crop.

**Comment by d4mation** [comment] 2016-05-20 14:10
Went for an SVG clip this time rather than pure CSS so I could get those curves on the sprockets done nicely. Hopefully it works in IE 🙈 Downloading some VMs now to test.

![image](https://cloud.githubusercontent.com/assets/7770631/15430305/bc8592e4-1e72-11e6-88d4-471e52aaff6e.png)

**Comment by d4mation** [comment] 2016-05-20 18:31
After what feels like centuries, I've got it working in IE 11 (Timestamp is incorrect&mdash;, using a VM).

![image](https://cloud.githubusercontent.com/assets/7770631/15437871/52f1468c-1e97-11e6-88c7-ef8ac174ff1b.png)

Going to try testing back a couple versions of IE as well. SVGs are pretty tricky cross-browser, but for a shape like this it was likely overall easier than using pure CSS.

**Comment by brashrebel** [comment] 2016-05-21 16:16
That's amazing. I love it.

**Comment by d4mation** [comment] 2016-05-23 14:30
It is now working correctly in the latest Chrome, Firefox, Safari, and IE 9-11 (Possibly 8, but I was testing in JSFiddle and that wouldn't load in IE 8 for me).

Now I've just got to translate the mockups into something real, which should be much simpler 👍 

[Here's the Fiddle, for anyone possibly interested](https://jsfiddle.net/d4mation/eggg4x2j/)

**Comment by d4mation** [comment] 2016-05-23 18:38
Here's a sneak-peek:

![image](https://cloud.githubusercontent.com/assets/7770631/15480088/a06d2898-20f1-11e6-803a-6a484a0d3d82.png)

On even rows, I'm tilting the gears slightly, that way they appear to "match up". Conveniently, that could also visually represent that we all work together as one "machine". Unfortunately, since @joelworsham is currently on the second row his eye gets cut off. 🙊 We may want to rearrange things so that doesn't happen. Alternatively, we can decide against tilting the gears.

All I've got to implement still are hover-overlays for our names/titles and re-adding in a link to our profiles.

I've set up some rather complicated logic to ensure this expands going into the future without any need for intervention/recoding. I've included a crude diagram of different layouts (Asterisks are gears).

However, currently this logic doesn't work very well for 6, 7, or 9 Staff Members for example. We'd get some orphans hanging down below unless we add another conditional for have them revert to another layout. Any ideas for handling that are appreciated.

1 Staff Member
```
-------------
------*------
-------------
```

2 Staff Members
```
--------------
---*------*---
--------------
```

3 Staff Members
```
--------------
--*---*---*--
--------------
```

4 Staff Members
```
--------------
---*------*---
-----*--*-----
--------------
```

5+ Staff Members. As many gears that are needed are added following this pattern.
```
-------------
---*--*--*---
-----*--*----
---*--*--*---
-------------
```

**Comment by BigActual** [comment] 2016-05-23 20:11
In your mockup we all seem, proportionately, quite large. Try knocking us down to 2/3 of the size. May have you go smaller. Let's see it pushed to a dev site or something.

**Comment by brashrebel** [comment] 2016-05-23 20:27
I personally like them large like that.

**Comment by BigActual** [comment] 2016-05-23 20:31
No

**Comment by d4mation** [comment] 2016-05-23 20:34
Here's a quick mockup of gears at `66%` of their current size (I used some CSS Transforms, to do it properly I need to remake the SVG). The weirdness with the gradient at the bottom is caused by the color shifting as you scroll and my screenshot triggered it weird.

![image](https://cloud.githubusercontent.com/assets/7770631/15483691/f9ad2784-2103-11e6-8d71-3b6496b3baf2.png)

I'm going to set up their current sizes on Staging. Might take a minute or two.

**Comment by BigActual** [comment] 2016-05-23 20:40
Love it.

**Comment by d4mation** [comment] 2016-05-23 20:58
Staging for the `rbmin` install was acting strange and redirecting every install to Real Big Plugins Staging, so I had to make some destructive changes. ***Staging should not be merged on-top of Live for this install until this is reverted. It will prevent the other sites within the multisite from loading.***

The large version of the gears can be seen here: http://rbmin.staging.wpengine.com/about/

My only concern with the smaller gears is that I was going to have our names/titles appear on hover similar to how they are on the Live site now and having smaller gears means less room for the text.

**Comment by BigActual** [comment] 2016-05-23 21:03
This is the only place on the site where I see a black outline. I believe everything else is just flat (for lack of a more thought out description), not outlines.

**Comment by d4mation** [comment] 2016-05-23 21:06
I just removed them on the Staging site. I had originally placed them there since without them there isn't a very clear distinction between the shape and the background.

![image](https://cloud.githubusercontent.com/assets/7770631/15484572/a059f7c0-2108-11e6-926e-b406e363ef40.png)

Maybe we could use a dark green outline instead?

**Comment by d4mation** [comment] 2016-05-23 21:08
I just redeployed to Staging as I'm having WP Engine look into the problem I mentioned above, so the URL for Staging won't work for the time being.

**Comment by BigActual** [comment] 2016-05-23 21:43
Much better w/o, but it looks like they grew again.

**Comment by d4mation** [comment] 2016-05-23 22:12
Yeah, I had only done something very temporary earlier to show what they could look like smaller. I will need to recreate the SVG for the gear shape to make it smaller as scaling SVGs does not work very well cross-browser.

I'll work on getting it recreated for a smaller size.

**Comment by d4mation** [comment] 2016-05-23 22:33
I've sized down the gears on Staging to be `66%` of their original size. Since they no longer have a border (Which was technically created by having another, non-clipped shape behind the profile images), it was a bit easier to resize them than they would have been otherwise.

**Comment by BigActual** [comment] 2016-05-23 22:52
Yeup. That's sweet. Nice.

**Comment by BigActual** [comment] 2016-05-23 22:56
Anything keeping from closing this issue?

**Comment by d4mation** [comment] 2016-05-23 23:04
Still have to implement our names/titles on hover. Now that the gears are smaller, I may have to instead place them below the gears using some kind of banner as longer names/titles may not fit nicely inside the gears.

**Comment by joelworsham** [comment] 2016-05-24 11:45
Man, I was with @brashrebel. I liked them better a bit bigger.

Also, there's no name now when hovering, because it can't fit. Can you find a way to incorporate the name and positions? Even if it's just under or above or on hover or something.

**Comment by d4mation** [comment] 2016-05-24 12:34
Yeah, I'm with you @joelworsham. I was going to put them in as overlays similar to how they were before, but I'm not sure if I can do it so simply now that they are smaller. I've been thinking perhaps a banner along the bottom of the gear that appears on hover.

**Comment by d4mation** [comment] 2016-05-24 13:50
![image](https://cloud.githubusercontent.com/assets/7770631/15506228/d58b1e6a-2194-11e6-8f6b-81a1765bcf42.png)

Fades into view on Hover with a `100ms` delay so it begins to appear after the gear starts to scale up. Our names use the `font-size` of an `h4` and our titles use the `font-size` of an `h5`.

I thought clipping it to the same shape would be cool, but we don't have a lot of space to work with and most of our titles would spill out of the edges slightly and be lost.

Changes will be viewable on Staging shortly.

**Comment by d4mation** [comment] 2016-05-24 14:52
It is working in the latest Chrome, Firefox and IE 9-11 flawlessly currently.

In Safari, there's a slight bug with how it is positioning the text:

![image](https://cloud.githubusercontent.com/assets/7770631/15508365/22b7cf96-219d-11e6-9685-43320904d16d.png)

I'm thinking it is related to the contents of [this article](http://opticalcortex.com/svg-rendering-in-browsers/). However, since the alignment issues only seem to apply to the very basic `<text>` elements, I'm not sure what can really be done about it. Changing the `y` values would fix it for Safari, but break it everywhere else. CSS doesn't seem to affect it either (And targeting just Safari via CSS would be ridiculous).

**Comment by d4mation** [comment] 2016-05-24 18:14
I've been brainstorming the "orphaned gears" problem and I think I've come up with a solution. It is unfortunately verbose, but it should cover just about any use case.

At 5+ Staff Members, we are following this pattern:
```
-------------
---*--*--*---
-----*--*----
-------------
```

Which repeats indefinitely. Basically, it is based on the same repeating 5 gears.

I figure that since it is based on 5, we could do some modulus division to determine what to do in cases where the number of Staff Members doesn't divide equally into 5.

For example:

`6 % 5 = 1`
```
-------------
---*--*--*---
-----*--*----
-------*-----
-------------
```

`7 % 5 = 2`
```
-------------
---*--*--*---
-----*--*----
---*-----*---
-------------
```

`9 % 5 = 4`
```
-------------
---*--*--*---
-----*--*----
---*--*--*---
------*------
-------------
```

In the case of `8 % 5 = 3` or `10 % 5 = 0`, it by default leaves us with a nice, finished pattern so nothing special should need to be done. So, we basically have slightly varied patterns if the result of the modulus division is `1`, `2`, or `4` as those are the only possible results other than `3` or `0` which we will just ignore and treat normally. 

Once this is taken care of, I'd feel comfortable closing this Issue and moving these changes to Live.

**Closed** 2016-05-24 20:45 UTC
Labels: enhancement

**Comment by d4mation** [comment] 2016-05-24 20:47
Modulus cases are implemented! :tada:

I tested each possibility from 1-14 Staff Members and everything worked as it should following all my really crude diagrams from above. Given the nature of modulus division, going up through infinity things should always work the same.

The current revision is up on Staging. If all looks good to you guys, I'll go ahead and SFTP these changes to Live.
